
[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Custom domain configuration
[build.environment]
  NETLIFY_SITE_NAME = "cannabisnob.de"

